// frontend/src/lib/constants.ts

const LOCAL_ESCROW_FALLBACK_ADDRESSES = [
  "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512", // Foundry default local deploy
  "0x5FbDB2315678afecb367f032d93F642f64180aa3", // Hardhat default local deploy
];

export const TEE_ORACLE_ADDRESS =
  process.env.NEXT_PUBLIC_TEE_ORACLE_ADDRESS ?? "0xFCAd0B19bB29D4674531d6f115237E16AfCE377c";

export const ESCROW_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_ESCROW_CONTRACT_ADDRESS ?? LOCAL_ESCROW_FALLBACK_ADDRESSES[0];

export const ESCROW_ADDRESS_CANDIDATES = [
  ESCROW_CONTRACT_ADDRESS,
  ...LOCAL_ESCROW_FALLBACK_ADDRESSES.filter(
    (address) => address.toLowerCase() !== ESCROW_CONTRACT_ADDRESS.toLowerCase(),
  ),
];

// Human-readable ABI format for Ethers.js.
// We only define the functions used by the frontend.
export const ESCROW_ABI = [
  // Buyer locks funds in escrow (payable so ETH can be sent).
  "function lockFunds() external payable",
  
  // Releases funds using a signature generated by the TEE.
  "function releaseFundsWithSignature(bytes memory signature) external",
  
  // Read-only contract state helpers.
  "function buyer() external view returns (address)",
  "function teeOracle() external view returns (address)",
  "function lockedAmount() external view returns (uint256)",
  "function isCompleted() external view returns (bool)"
];
